### ISSUE TITLE
Werte die über getCharacteristic* kommen validieren

### ISSUE THREAD

**Issue by paresy** [paresy/HomeKit#13]
HomeKit mag es gar nicht, wenn man Werte sendet, welche nicht innerhalb der Spezifikation der "Characteristic" sind. Wir sollten das validieren und entsprechend bemängeln, bevor wir falsche Werte schicken.

**Comment by Schnittcher** [comment]
Also den Datentyp der Variable abfragen und mit HAPCharacteristicFormat vergleichen?

**Comment by paresy** [comment]
Beides. Entmal der Typ muss stimmen (Also es darf kein String kommen, wenn Int gefordert wird) und der Bereich muss stimmen. (Es darf keine 60 kommen, wenn maximal 50 zulässig ist)

Der Check müsste hier rein: https://github.com/paresy/HomeKit/blob/master/HomeKitBridge/hap.php#L90

Und dazu passend eine private validateCharacteristicValue() Funktion würde ich mir vorstellen.

**Comment by Schnittcher** [comment]
https://github.com/paresy/HomeKit/pull/20

**Comment by paresy** [comment]
Ich habe die Validierung mal eingebaut für Lesen und Schreiben der Werte: https://github.com/paresy/HomeKit/commit/8457c7cb11743590487b31b0d643f760d986bb9b
