### ISSUE TITLE
Lightbulb (Dimmer) and Philips HUE not working correctly

### ISSUE THREAD

**Issue by erykio** [paresy/HomeKit#70]
I have a Lightbulb (Dimmer) in HomeKit to control my Philips HUE Light. 

The problem is that when I switch off the HUE Light in the Webfront, the light gets status OFF and brightness stays the same (e.g. 80%). In HomeKit this shows the light as ON, which is incorrect.

Also switching from HomeKit does not work very well. When I turn the light ON in HomeKit, it works well. But when switching OFF the light in HomeKit, the HUE brightness is set to a value of 0, and after a few seconds it is set to a value of 1 (which is 1/255=0,39%) and shows in the Webfront and HomeKit as 0%, but in HomeKit with status ON. 

I'm not sure where this bug comes from, but maybe the lightbulbDimmer.php should use both the Brightness and Status values to determine it's status. 
The value 1 issue could be a decimal rounding bug?

(Using IPS 5.0)

**Comment by paresy** [comment]
Hi,

can you please verify if switching from WebFront will properly update all variables? AFAIK the Hue module does not play well with our HomeKit module, which requires definitive states in one variable (either switch or dimmer). Probably you will need to file a bug report in the Hue module.
