### ISSUE TITLE
Dimmer geht erst auf 100% um später auf den korrekten Wert zu dimmen

### ISSUE THREAD

**Issue by paresy** [paresy/HomeKit#88]
Potenziell unvollständiger Workaround: https://www.symcon.de/forum/threads/42607

Das Problem it, dass Apple ein ON sendet, wodurch wir die Lampe erst einmal anschalten, sofern diese nicht an ist. Danach erst triggert das eigentliche Dimmen auf den korrekten Wert.

Wir könnten das Ereignis auf On/Off deaktivieren. Dann wird vermutlich die simple An/Aus Variante (wenn man auf die Kachel klickt) nicht mehr korrekt gehen.

**Comment by Schnittcher** [comment]
Mit Lampe (Expert), wäre das Problem gelöst.
Dort schalte ich auf den vor eingestellten Wert.

**Comment by Schnittcher** [comment]
Lampe (Expert) ist als Beta Version verfügbar.
