### ISSUE TITLE
iOS 14.3 can't add accessories

### ISSUE THREAD

**Issue by mohamedabdelaalkhalifa** [paresy/HomeKit#91]
Dear Sir,
Please note that while trying to add a new Home, the phone is keep searching for the accessions without luck. also, after adding the  8 paring characters.
Please Advise!

**Comment by paresy** [comment]
Hi,

you can elaborate on your setup? Which platform? Did you disable firewalls? 

Did i understand correctly, that you can see the bridge initially in the app?

**Comment by mohamedabdelaalkhalifa** [comment]
Hello Paresy,
Thanks for your reply. Please note that I installed the module as normal from the IP-Symcon module store and socket is activated. I added dome switched and status is OK then requested a setup key to pair with iOS Home. iPhone is keep searching for the accessories without finding the bridge also after adding the code manual. Please note, Firewall is disabled in the server.
Please Advise!
Thanks

**Comment by mohamedabdelaalkhalifa** [comment]
Can you try from your side after upgrading iPhone to iOS 14.3 ?

**Comment by paresy** [comment]
Which IP-Symcon Version do you use and on which platform? (Windows? Raspberry?)

**Comment by mohamedabdelaalkhalifa** [comment]
IP-Symcon 5.5 and Windows 10 Pro x64

**Comment by mohamedabdelaalkhalifa** [comment]
Dear Paresy,
Your advise is highly appreciated. Thanks

**Comment by mohamedabdelaalkhalifa** [comment]
Any updates ? I'm sure there is a compatibility issue with the new iOS 14.3
Please Advise!

**Comment by paresy** [comment]
I can't confirm any issues with 14.3 which i also use myself. Therefore it has to be an issue with the firewall, your network setup (does it filter Multicast somehow?) or the configuration itself.

**Comment by paresy** [comment]
Further discussion is here: https://www.symcon.de/forum/threads/45358

**Comment by mohamedabdelaalkhalifa** [comment]
Dear Paresy,
I want to confirm that there is something wrong maybe with the new IP-Symcon 5.5 latest update compatibility with the HomeKit. I'm sure because I deleted my Windows installation and tried to install a fresh install on Ubuntu with the same behavior.
Please note that the configuration is NOT a big story. Just installing the module from the module-store then activating the socket then add a switch for testing then apply. iOS keep searching for the bridge for a long time even also with adding the code manual.
Note: I installed https://github.com/homebridge/homebridge in the same server and working fine without any problem. iOS was able to pair the bridge without any problem.
Please review and advise
Thanks
