### ISSUE TITLE
Dokumentation in Wiki Funktion migrieren

### ISSUE THREAD

**Issue by GregTCLTK** [paresy/HomeKit#92]
Ich denke es wäre von Vorteil die bereits vorhandene Dokumentation, welche im /docs Ordner gespeichert wird, in die bereits seit längerem vorhandene [Wiki Funktion von GitHub](https://docs.github.com/en/github/building-a-strong-community/about-wikis) zu migrieren.

**Comment by paresy** [comment]
Hi Greg,

was wäre deiner Meinung nach der Vorteil? Du kannst für die Dokumentation hier jederzeit Verbesserungen als PR einreichen :)

**Comment by GregTCLTK** [comment]
Ich denke, dass die GitHub Wiki Funktion eine eindeutig bessere Übersichtlichkeit bietet als ein docs folder mit markdown files.

**Comment by paresy** [comment]
Da es aktuell kein Feedback mehr dazu gab würde ich hier schließen. Falls du die normale Dokumentation verbessern möchtest, würden wir uns natürlich sehr freuen!
