### ISSUE TITLE
2 Homekit Instancen möglich?

### ISSUE THREAD

**Issue by dr-apple** [paresy/HomeKit#93]
Ich versuche gerade in Symcon 6 2 Homekit Instancen zum laufen zu bekommen.

Ich habe schon den Namen, Mac und Port unterschiedlich für beide Instancen gemacht und habe auch die alten DNS-SD Einträge gelöscht.

Es wird beide Instancen angezeigt aber ich kann mich nur mit einer verbinden, die zweite Instance schlägt immer fehl :-(

**Comment by paresy** [comment]
Sorry für die späte Antwort. Klar geht das. Sind aber überall die Namen und Port in den Experten Einstellungen unterschiedlich?
