### ISSUE TITLE
HomeKit Bridge :: Instance is using the server socket dataflow packet but is missing the Type field. This will stop working in the future ...

### ISSUE THREAD

**Issue by PreinfalkG** [paresy/HomeKit#94]
Guten morgen

Seit dem Update auf v6.1 sind in meinem IP-Symcon Log sehr viele dieser Einträge zu finden -> **siehe Screenshot**
Ich denke, dass ist zwar derzeit kein funktionales Problem aber leider wird das LogFile dadurch relative groß bzw. gehen anderer Meldungseinträge dadurch fast unter ...

Wenn ich mit nicht irre, kommen diese Einträge von der Konfigurator Instanz der HomeKitBridge        
_Einträge sind:  **Instance is using the server socket dataflow packet but is missing the Type field. This will stop working in the future.**_

_Zusatz: Bei mir sind es genau jede Minute 31 Einträge (denke das ist die Anzahl meiner Geräte)_

Screenshot:
![image](https://user-images.githubusercontent.com/16906959/151492035-523375ea-c8f8-4032-8490-33139cac10e6.png)

**Comment by paresy** [comment]
Danke für den ausführlichen Report. Das problem sollte bereits in der Beta Version vom Modul gelöst sein :)

**Comment by PreinfalkG** [comment]
! Vielen DANK !
Ich habe die Beta Version vom Modul installiert und die Log Einträge sind 'Vergangenheit'

Lg. Günter
