### ISSUE TITLE
Lampe (Experte) Kann Daten nicht zur Instanz #43995 weiterleiten seit letztem Update

### ISSUE THREAD

**Issue by Chilled** [paresy/HomeKit#95]
Seit dem letzten Update bekomme ich folgende Fehlermeldung in Kombination mit einem Shelly Dimmer2

`10.05.2022, 21:02:47 | FlowHandler          | Kann Daten nicht zur Instanz #43995 weiterleiten: 
Fatal error: Uncaught Error: Call to private method HAPAccessoryLightbulbSwitch::switchDevice() from context 'HAPAccessoryLightbulbExpert' in /var/lib/symcon/modules/.store/de.paresy.homekit/HomeKitBridge/accessories/lightbulbExpert.php:25
Stack trace:
#0 /var/lib/symcon/modules/.store/de.paresy.homekit/HomeKitBridge/hap.php(120): HAPAccessoryLightbulbExpert->writeCharacteristicOn(1)
#1 /var/lib/symcon/modules/.store/de.paresy.homekit/HomeKitBridge/hap.php(58): HAPService->writeCharacteristic(2, 1, Object(HAPAccessoryLightbulbExpert))
#2 /var/lib/symcon/modules/.store/de.paresy.homekit/HomeKitBridge/manager.php(317): HAPAccessory->writeCharacteristic(102, 1)
#3 /var/lib/symcon/modules/.store/de.paresy.homekit/HomeKitBridge/session.php(1092): HomeKitManager->writeCharacteristics(44, 102, 1)
#4 /var/lib/symcon/modules/.store/de.paresy.homekit/HomeKitBridge/session.php(241): HomeKitSession->writeCharacteristics(Array)
#5 /var/lib/symcon/modules/.store/de.paresy.homekit/HomeKitBridge/module.php(215): HomeKitSession->processDa in /var/lib/symcon/modules/.store/de.paresy.homekit/HomeKitBridge/accessories/lightbulbExpert.php on line 25
`

**Comment by paresy** [comment]
Danke. Sollte mit https://github.com/paresy/HomeKit/commit/e9f5ec28cc68a3880060bc0be70560daefec2f99 gefixt sein. Neue Version auch über den Module Store verfügbar!
